name: vpn
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+30

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  rxdart: ^0.27.7
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.7.0
  internet_connection_checker: ^1.0.0+1
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  flutter_screenutil: ^5.9.1
  fast_rsa: ^3.6.2
  pointycastle: ^3.9.1
  uuid: ^4.4.0
  auto_route: ^8.1.3
  percent_indicator: ^4.2.3
  flutter_keyboard_visibility: ^6.0.0
  basic_utils: ^5.7.0
  device_info_plus: ^10.1.0
  lottie: ^3.1.2
  encrypt: ^5.0.3
  another_flutter_splash_screen: ^1.2.0
  sign_in_with_apple: ^6.1.0
  google_sign_in: ^6.2.1
  cherry_toast: ^1.10.1
  flag: ^7.0.0
  intl: ^0.19.0
  speed_test_dart: ^1.0.5+0
  webview_flutter: ^4.8.0
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4
  cloud_firestore: ^4.17.5
  flutter_local_notifications: ^9.7.0
  url_launcher: ^6.2.6
  in_app_purchase: ^3.1.11
  flutter_secure_storage: ^9.2.2
  easy_localization: ^3.0.7
  focus_detector: ^2.0.1
  logger: ^2.3.0
  http_interceptor: ^2.0.0-beta.8
  cupertino_http: ^1.5.0
  responsive_builder: ^0.7.0
  # firebase_core_platform_interface: 5.0.0
  window_manager: ^0.3.9
  package_info_plus: ^8.0.0
  device_preview: ^1.2.0
  
  
  




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.8
  

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/

  fonts:
    - family: Roboto
      fonts:
          - asset: assets/fonts/roboto/Roboto-Black.ttf
            weight: 900
          - asset: assets/fonts/roboto/Roboto-BlackItalic.ttf
            weight: 900
            style: italic
          - asset: assets/fonts/roboto/Roboto-Bold.ttf
            weight: 700
          - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
            weight: 700
            style: italic
          - asset: assets/fonts/roboto/Roboto-Italic.ttf
            style: italic
          - asset: assets/fonts/roboto/Roboto-Light.ttf
            weight: 300
          - asset: assets/fonts/roboto/Roboto-LightItalic.ttf
            weight: 300
            style: italic
          - asset: assets/fonts/roboto/Roboto-Medium.ttf
            weight: 500
          - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
            weight: 500
            style: italic
          - asset: assets/fonts/roboto/Roboto-Regular.ttf
          - asset: assets/fonts/roboto/Roboto-Thin.ttf
            weight: 100
          - asset: assets/fonts/roboto/Roboto-ThinItalic.ttf
            weight: 100
            style: italic
    - family: Saira
      fonts:
          - asset: assets/fonts/saira/Saira-Black.ttf
          - asset: assets/fonts/saira/Saira-BlackItalic.ttf
          - asset: assets/fonts/saira/Saira-Bold.ttf
          - asset: assets/fonts/saira/Saira-BoldItalic.ttf
          - asset: assets/fonts/saira/Saira-ExtraBold.ttf
          - asset: assets/fonts/saira/Saira-ExtraBoldItalic.ttf
          - asset: assets/fonts/saira/Saira-ExtraLight.ttf
          - asset: assets/fonts/saira/Saira-ExtraLightItalic.ttf
          - asset: assets/fonts/saira/Saira-Italic.ttf
          - asset: assets/fonts/saira/Saira-Light.ttf
          - asset: assets/fonts/saira/Saira-LightItalic.ttf
          - asset: assets/fonts/saira/Saira-Medium.ttf
          - asset: assets/fonts/saira/Saira-MediumItalic.ttf
          - asset: assets/fonts/saira/Saira-Regular.ttf
          - asset: assets/fonts/saira/Saira-SemiBold.ttf
          - asset: assets/fonts/saira/Saira-SemiBoldItalic.ttf
          - asset: assets/fonts/saira/Saira-Thin.ttf
          - asset: assets/fonts/saira/Saira-ThinItalic.ttf




  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: assets/fonts/saira/Schyler-Regular.ttf
  #       - asset: assets/fonts/saira/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/saira/TrajanPro.ttf
  #       - asset: assets/fonts/saira/TrajanPro_Bold.ttf
  #         weight: 700