name: vpn
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  dio: ^5.3.2
  flutter_bloc: ^8.1.1
  bloc: ^8.1.2
  rxdart:
  equatable: ^2.0.3
  dartz: ^0.10.1
  get_it: ^7.2.0
  internet_connection_checker: ^0.0.1+4
  flutter_svg:
  animated_bottom_navigation_bar: ^1.3.2
  provider: ^6.0.5
  flutter_screenutil: ^5.7.0
  flutter_vpn: ^0.12.0
  fast_rsa: ^3.6.1
  pointycastle: ^3.7.4
  uuid:
  cryptography: ^2.7.0
  auto_route: ^7.8.4
  percent_indicator: ^4.2.3
  flutter_keyboard_visibility: ^6.0.0
  basic_utils: ^5.7.0
  gif: ^2.3.0
  device_info_plus: ^9.1.2
  lottie:
  encrypt: ^5.0.3
  flutter_native_splash:
  another_flutter_splash_screen: ^1.2.0
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.1.4



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
          - asset: assets/fonts/roboto/Roboto-Black.ttf
            weight: 900
          - asset: assets/fonts/roboto/Roboto-BlackItalic.ttf
            weight: 900
            style: italic
          - asset: assets/fonts/roboto/Roboto-Bold.ttf
            weight: 700
          - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
            weight: 700
            style: italic
          - asset: assets/fonts/roboto/Roboto-Italic.ttf
            style: italic
          - asset: assets/fonts/roboto/Roboto-Light.ttf
            weight: 300
          - asset: assets/fonts/roboto/Roboto-LightItalic.ttf
            weight: 300
            style: italic
          - asset: assets/fonts/roboto/Roboto-Medium.ttf
            weight: 500
          - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
            weight: 500
            style: italic
          - asset: assets/fonts/roboto/Roboto-Regular.ttf
          - asset: assets/fonts/roboto/Roboto-Thin.ttf
            weight: 100
          - asset: assets/fonts/roboto/Roboto-ThinItalic.ttf
            weight: 100
            style: italic
    - family: Saira
      fonts:
          - asset: assets/fonts/saira/Saira-Black.ttf
          - asset: assets/fonts/saira/Saira-BlackItalic.ttf
          - asset: assets/fonts/saira/Saira-Bold.ttf
          - asset: assets/fonts/saira/Saira-BoldItalic.ttf
          - asset: assets/fonts/saira/Saira-ExtraBold.ttf
          - asset: assets/fonts/saira/Saira-ExtraBoldItalic.ttf
          - asset: assets/fonts/saira/Saira-ExtraLight.ttf
          - asset: assets/fonts/saira/Saira-ExtraLightItalic.ttf
          - asset: assets/fonts/saira/Saira-Italic.ttf
          - asset: assets/fonts/saira/Saira-Light.ttf
          - asset: assets/fonts/saira/Saira-LightItalic.ttf
          - asset: assets/fonts/saira/Saira-Medium.ttf
          - asset: assets/fonts/saira/Saira-MediumItalic.ttf
          - asset: assets/fonts/saira/Saira-Regular.ttf
          - asset: assets/fonts/saira/Saira-SemiBold.ttf
          - asset: assets/fonts/saira/Saira-SemiBoldItalic.ttf
          - asset: assets/fonts/saira/Saira-Thin.ttf
          - asset: assets/fonts/saira/Saira-ThinItalic.ttf




  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: assets/fonts/saira/Schyler-Regular.ttf
  #       - asset: assets/fonts/saira/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/saira/TrajanPro.ttf
  #       - asset: assets/fonts/saira/TrajanPro_Bold.ttf
  #         weight: 700
