name: vpn
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  dio: ^5.3.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.3
  dartz: ^0.10.1
  get_it: ^7.2.0
  internet_connection_checker: ^0.0.1+4
  flutter_svg:
  animated_bottom_navigation_bar: ^1.3.2
  provider: ^6.0.5
  flutter_screenutil: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Saira
      fonts:
          - asset: assets/fonts/saira/Saira-Black.ttf
          - asset: assets/fonts/saira/Saira-BlackItalic.ttf
          - asset: assets/fonts/saira/Saira-Bold.ttf
          - asset: assets/fonts/saira/Saira-BoldItalic.ttf
          - asset: assets/fonts/saira/Saira-ExtraBold.ttf
          - asset: assets/fonts/saira/Saira-ExtraBoldItalic.ttf
          - asset: assets/fonts/saira/Saira-ExtraLight.ttf
          - asset: assets/fonts/saira/Saira-ExtraLightItalic.ttf
          - asset: assets/fonts/saira/Saira-Italic.ttf
          - asset: assets/fonts/saira/Saira-Light.ttf
          - asset: assets/fonts/saira/Saira-LightItalic.ttf
          - asset: assets/fonts/saira/Saira-Medium.ttf
          - asset: assets/fonts/saira/Saira-MediumItalic.ttf
          - asset: assets/fonts/saira/Saira-Regular.ttf
          - asset: assets/fonts/saira/Saira-SemiBold.ttf
          - asset: assets/fonts/saira/Saira-SemiBoldItalic.ttf
          - asset: assets/fonts/saira/Saira-Thin.ttf
          - asset: assets/fonts/saira/Saira-ThinItalic.ttf




  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: assets/fonts/saira/Schyler-Regular.ttf
  #       - asset: assets/fonts/saira/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/saira/TrajanPro.ttf
  #       - asset: assets/fonts/saira/TrajanPro_Bold.ttf
  #         weight: 700
