// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcyqgAtbk9HYr9oc3f25RxEwjelCyRLyc',
    appId: '1:440899395030:web:aa31fa0429de28e95b5877',
    messagingSenderId: '440899395030',
    projectId: 'vpn-line',
    authDomain: 'vpn-line.firebaseapp.com',
    storageBucket: 'vpn-line.appspot.com',
    measurementId: 'G-62H174CGM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9pAl-tdIAuEEV_bj5Ah4T2FjQgUctNsM',
    appId: '1:440899395030:android:231cee1f42dd2d295b5877',
    messagingSenderId: '440899395030',
    projectId: 'vpn-line',
    storageBucket: 'vpn-line.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbCwzAyKA35UU_75GktisSxRkGXsMypjg',
    appId: '1:440899395030:ios:397d2e55d7210e165b5877',
    messagingSenderId: '440899395030',
    projectId: 'vpn-line',
    storageBucket: 'vpn-line.appspot.com',
    iosBundleId: 'org.cnddrm.vp-line-app.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbCwzAyKA35UU_75GktisSxRkGXsMypjg',
    appId: '1:440899395030:ios:397d2e55d7210e165b5877',
    messagingSenderId: '440899395030',
    projectId: 'vpn-line',
    storageBucket: 'vpn-line.appspot.com',
    iosBundleId: 'org.cnddrm.vp-line-app.RunnerTests',
  );
}
