# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches:
    - main
    - dev
    - release/*

jobs:
  build:
    runs-on: ubuntu-latest

   
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.1'
    - run: flutter pub get
    - run: flutter build apk
    - run: flutter build appbundle
    - run: flutter build ios --release --no-codesign
    
            
